sudo: false
language: node_js
node_js:
  - "6.1"
env:
  global:
    - NODE_ENV=production
    - AWS_ACCESS_KEY_ID=AKIAJ6WHH6ZDLBELE62A
    - secure: "PWxI0QNKnvHwxwqImBXqyBUWXZWCMNGvlfXbVy8dfvQhYXLEKamqJfTGYp6nB5sVMH4xJH8Qgl0nOFf/blW5XXTk5O07LBkL1v2br3lto/leWpGkVRy17ymu1BtjYOLUhBPrrePF8hHqLynMgV10rAsJFjuqWpjfaCX890KtYw0="
install:
  - for f in .modules/*.tgz; do tar -zxf "$f" -C node_modules/; done
  - npm rebuild
script:
  - ./node_modules/gulp/bin/gulp.js publish

