sudo: false
language: node_js
node_js:
  - "4.2.4"
env:
  global:
    - NODE_ENV=production
    - AWS_ACCESS_KEY_ID=AKIAJCPKMW75PSFUC2LQ
    - secure: "Befk9OSMDwfgs5JmoVAzotEuWlndATyZ7nTJBI8AwX7s8GWYBO8oiYPz3HAX1fKV4limqMXxLPjALpVDhLyvwSaYJlinzOp1VfXpLBjaG6fX7A6gLIJJN0xccJDZ43UnoF3q3tbAOjaO6VR6Qm4TeSuJJX0+uq9BOHwfkWesJLM="
install:
  - for f in .modules/*.tgz; do tar -zxf "$f" -C node_modules/; done
script:
  - ./node_modules/gulp/bin/gulp.js publish

