name: Michal Charemza
pygments: true
assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/partials
    - _assets/stylesheets
  # Files are zipped by s3_website
  gzip: false
  css_compressor: sass
#  baseurl: //assets.charemza.name/assets/
permalink: blog/posts/:categories/:title
url: http://charemza.name
exclude: 
  - s3_website.yml
  - node_modules
  - Gruntfile.js
  - npm-debug.log
sitemap:
  file: sitemap.xml
  include: index.html