name: Michal Charemza
source: src
destination: build
highlighter: true
assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
  # Files are zipped by s3_website
  gzip: false
  css_compressor: sass
#  baseurl: //assets.charemza.name/assets/
permalink: blog/posts/:categories/:title
url: http://charemza.name
exclude: 
  - .DS_Store
  - .gitignore
sitemap:
  file: sitemap.xml
  include: index.html

